import { Sen } from "next/font/google";
import "./globals.css";
//COmponents
import Header from "@/components/Header";
import Fototer from "@/components/Fototer";
//Theme Provider
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Sen({ subsets: ["latin"],
weight:['400','500','600','700'],
display:'swap'
 });
 

export const metadata = {
  title: "Scynaero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='light' >
        <Header/>
        {children}
        <Fototer/>
        </ThemeProvider>
        
        </body>
    </html>
  );
}
